### PR TITLE
Don't generate core name when adding core to corepool.

### LINKED ISSUE #124: casadm --script --add-core --try-add fails if there is no cache with cache_id
casadm --script --add-core --try-add --cache-id 1 --core-device /dev/sdX should work regardless of (non)existing cache with cache_id

### PR DESCRIPTION
**Pull request by mmichal10**
When core frome corepool is added to cache, it's old name is loaded and cores
in corepool cannot be referenced by name anyway so new name is not needed.

Fixes #124 

Signed-off-by: Michal Mielewczyk <michal.mielewczyk@intel.com>

### CODE REVIEW

File: modules/cas_cache/layer_cache_management.c [hunk 1]
```diff
@@ -534,8 +534,7 @@ int cache_mngt_prepare_core_cfg(struct ocf_mngt_core_config *cfg,
 		struct kcas_insert_core *cmd_info)
 {
 	struct block_device *bdev;
-	static char core_name[OCF_CORE_NAME_SIZE];
-	struct cache_priv *cache_priv;
+	static char core_name[OCF_CORE_NAME_SIZE] = {};
```
Comment (robertbaldyga) [inline modules/cas_cache/layer_cache_management.c]: This shouldn't be static. It looks like it has been made static by mistake.

File: modules/cas_cache/layer_cache_management.c [hunk 2]
```diff
@@ -546,17 +545,19 @@ int cache_mngt_prepare_core_cfg(struct ocf_mngt_core_config *cfg,
 	if (cmd_info->core_id == OCF_CORE_MAX) {
 		result = mngt_get_cache_by_id(cas_ctx, cmd_info->cache_id,
 				&cache);
-		if (result)
+		if (result && result != -OCF_ERR_CACHE_NOT_EXIST) {
 			return result;
+		} else if (result != -OCF_ERR_CACHE_NOT_EXIST) {
+			struct cache_priv *cache_priv;
+			cache_priv = ocf_cache_get_priv(cache);
```
Comment (robertbaldyga) [inline modules/cas_cache/layer_cache_management.c]: So we are accessing `cache` despite getting it failed? It doesn't look good.
