### PR TITLE
Handle cache stopping interruption

### LINKED ISSUE #628: Interrupting a cache stop causes the threads suspension
## Description

Issue shows when sending the IOCTL request to stop the cache outside the casadm.

## Expected Behavior

The stop operation should finish without leaving any processes.
Cas_cache's refcnt shall be 0 after stopping the only cache.

## Actual Behavior

CAS informs that the cache has been successfully stopped but has actually left zombie processes.
Each unfinished stop leaves cas_cache's refcnt incremented by 1.

## Steps to Reproduce

1. Send IOCTL request to stop the cache
2. Interrupt this operation
3. Wait for few seconds

## Context

This bug creates hung processes. Occurred during manual tests.

## Possible Fix

Finish the zombies.

## Logs

***DMESG***
```bash
[156582.533301] cache1: Flushing cache
[156582.540290] cache1: Flushing cache completed
[156582.546454] cache1: Flushing cache
[156582.550860] cache1: Flushing cache completed
[156582.556627] cache1: Stopping cache
[156582.561453] Thread cas_cl_cache1 stopped
[156589.806284] cache1: Done saving cache state!
[156589.815881] Thread cas_io_1_31 stopped
[156589.820994] Thread cas_io_1_30 stopped
[156589.825913] Thread cas_io_1_29 stopped
[156589.830781] Thread cas_io_1_28 stopped
[156589.835527] Thread cas_io_1_27 stopped
[156589.840348] Thread cas_io_1_26 stopped
[156589.845048] Thread cas_io_1_25 stopped
[156589.849730] Thread cas_io_1_24 stopped
[156589.854519] Thread cas_io_1_23 stopped
[156589.859283] Thread cas_io_1_22 stopped
[156589.864017] Thread cas_io_1_21 stopped
[156589.868736] Thread cas_io_1_20 stopped
[156589.873405] Thread cas_io_1_19 stopped
[156589.878121] Thread cas_io_1_18 stopped
[156589.882835] Thread cas_io_1_17 stopped
[156589.887539] Thread cas_io_1_16 stopped
[156589.892178] Thread cas_io_1_15 stopped
[156589.896876] Thread cas_io_1_14 stopped
[156589.901579] Thread cas_io_1_13 stopped
[156589.906211] Thread cas_io_1_12 stopped
[156589.910867] Thread cas_io_1_11 stopped
[156589.915551] Thread cas_io_1_10 stopped
[156589.920165] Thread cas_io_1_9 stopped
[156589.944339] Thread cas_io_1_8 stopped
[156589.948933] Thread cas_io_1_7 stopped
[156589.953528] Thread cas_io_1_6 stopped
[156589.958177] Thread cas_io_1_5 stopped
[156589.962821] Thread cas_io_1_4 stopped
[156589.967360] Thread cas_io_1_3 stopped
[156589.971906] Thread cas_io_1_2 stopped
[156589.976462] Thread cas_io_1_1 stopped
[156589.980969] Thread cas_io_1_0 stopped
[156589.985456] Cache cache1 successfully stopped
```

***OTHER***
```bash
root@localhost:~/open-cas-linux# ps aux | grep cas                                      
root      178643  0.0  0.0      0     0 ?        S    11:40   0:00 [cas_mu_cache1]      
root      178676  9.3  0.0      0     0 ?        D    11:40   0:54 [cas_mngt_1]         
root      178800  0.0  0.0      0     0 ?        D    11:42   0:00 [cas_cache1_stop]    
root      178942  0.0  0.0   6440   736 pts/1    S+   11:50   0:00 grep --color=auto cas
```

```bash
root@localhost:~/open-cas-linux# cat /proc/178800/stack
[<0>] kthread+0xe3/0x150                               
[<0>] ret_from_fork+0x22/0x30                          
```

```bash
root@localhost:~/open-cas-linux# cat /proc/178643/stack 
[<0>] _cas_metadata_updater_thread+0x99/0xd0 [cas_cache]
[<0>] kthread+0x114/0x150                               
[<0>] ret_from_fork+0x22/0x30                           
```

```bash
root@localhost:~/open-cas-linux# cat /proc/178676/stack
[<0>] _cas_stop_thread+0x53/0x70 [cas_cache]           
[<0>] cas_stop_queue_thread+0x2a/0x30 [cas_cache]      
[<0>] _cas_queue_stop+0xe/0x10 [cas_cache]             
[<0>] ocf_queue_put+0x54/0x70 [cas_cache]              
[<0>] ocf_req_put+0x85/0xc0 [cas_cache]                
[<0>] ocf_pipeline_destroy+0x17/0x30 [cas_cache]       
[<0>] ocf_mngt_cache_stop_finish+0xc3/0x100 [cas_cache]
[<0>] _ocf_pipeline_run_step+0x4f/0xd0 [cas_cache]     
[<0>] ocf_io_handle+0x34/0x40 [cas_cache]              
[<0>] ocf_queue_run_single+0x34/0x40 [cas_cache]       
[<0>] ocf_queue_run+0x2a/0x40 [cas_cache]              
[<0>] _cas_io_queue_thread+0x6f/0x110 [cas_cache]      
[<0>] kthread+0x114/0x150                              
[<0>] ret_from_fork+0x22/0x30                          
```

## Your Environment

* OpenCAS version (commit hash or tag): 20.12.0.0420.master 42c3f3ed8cf8ec8921abe976843ca5252abb653a
* Operating System: Ubuntu 20.4.1 LTS
* Kernel version: Linux 5.8.18
* Cache device type (model): INTEL SSDPED1K375GA
* Core device type (model): -
* Cache configuration:
* * Cache mode: (default: wt)
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

### PR DESCRIPTION
**Pull request by Ostrokrzew**
Ignore the interruption of the stop operation.
Move creating the `finish_thread` during the cache stop
from the `_cache_mngt_cache_stop_sync` to the `cache_mngt_exit_instance`
(one abstraction layer higher) and give it a proper handling.
Before waking up the `finish_thread` check if it is not unrunnable or broken.

Signed-off-by: Slawomir Jankowski <slawomir.jankowski@intel.com>

Fixes #628

### CODE REVIEW

**Review by rafalste — DISMISSED** [review]

File: modules/cas_cache/layer_cache_management.c [hunk 1]
```diff
@@ -585,8 +585,9 @@ static void _cache_mngt_cache_stop_complete(ocf_cache_t cache, void *priv,
 {
 	struct _cache_mngt_stop_context *context = priv;
 	context->error = error;
-
-	BUG_ON(!wake_up_process(context->finish_thread));
+	if (!IS_ERR(context->finish_thread)
```
Comment (mmichal10) [inline modules/cas_cache/layer_cache_management.c:588]: Since you performed this check on thread creation doing it here is redundant

File: modules/cas_cache/layer_cache_management.c [hunk 2]
```diff
@@ -585,8 +585,9 @@ static void _cache_mngt_cache_stop_complete(ocf_cache_t cache, void *priv,
...
+			&& (context->finish_thread->state != -1))
```
Comment (mmichal10) [inline modules/cas_cache/layer_cache_management.c:589]: Isn't this situation already handled by the line below?

File: modules/cas_cache/layer_cache_management.c (hunk 1 above)
Comment (Ostrokrzew) [reply modules/cas_cache/layer_cache_management.c]: Actually yes, You're right.

File: modules/cas_cache/layer_cache_management.c (hunk 2 above)
Comment (Ostrokrzew) [reply modules/cas_cache/layer_cache_management.c]: yes

File: modules/cas_cache/layer_cache_management.c [hunk 3]
```diff
@@ -2344,17 +2346,19 @@ int cache_mngt_exit_instance(const char *cache_name, size_t name_len, int flush)
...
+	/* Stop cache device - ignore interrupts */
 	status = _cache_mngt_cache_stop_sync(cache);
-	if (status == -ENOMEM)
-		goto unlock;
-
-	ocf_queue_put(mngt_queue);
+	if (status == -KCAS_ERR_WAITING_INTERRUPTED)
+		printk(KERN_WARNING
+				"An attempt to interrupt stopping cache "
+				"was made. Ignored.\n");
```
Comment (arutk) [inline modules/cas_cache/layer_cache_management.c:2354]: I wouldn't print "ignored" here. Maybe
Waiting for cache stop interrupted. Stop will finish asynchronously.

**Review by robertbaldyga — APPROVED** [review]

**Review by rafalste — APPROVED** [review]
