### PR TITLE
failover standby fixes

### LINKED ISSUE #998: [21.12] Kernel BUG on secondary node metadata_passive_update.c:181!
## Description

Not sure if an actual bug or just an unsupported scenario. Anyways CAS is in trace.

## Actual behavior
When cache was being started on the primary node before a cache DRBD device was fully synced, kernel BUG occurred on the secondary node.

## Steps to Reproduce

1. Start a standby cache on a secondary node
2. Configure and create a DRBD device (optane on primary + cas-cache-1 on secondary)
3. Set the device as primary on the primary node
4. Before the device is fully synced start a cache on the active node.

## Logs

```
[71022.961429] ------------[ cut here ]------------
[71022.971650] kernel BUG at /root/open-cas-linux/modules/cas_cache/src/ocf/metadata/metadata_passive_update.c:181!
[71022.987601] invalid opcode: 0000 [#1] SMP PTI
[71022.997737] CPU: 0 PID: 110378 Comm: drbd_r_caches-p Kdump: loaded Tainted: G           OE    --------- -  - 4.18.0-240.el8.x86_64 #1
[71023.037915] RIP: 0010:passive_io_resume+0x7ed/0x890 [cas_cache]
[71023.049866] Code: 00 e8 b7 56 ff ff 48 89 df e8 6f 79 00 00 85 c0 0f 84 94 fc ff ff 41 8b 86 a0 20 14 00 83 f8 02 0f 86 d9 fe ff ff 0f 0b 0f 0b <0f> 0b 0f 0b 0f 0b 0f 0b 0f 0b 0f 0b 0f 0b 0f 0b 49 8b 46 20 48 8b
[71023.081159] RSP: 0018:ffffb1b9e2f1fb18 EFLAGS: 00010297
[71023.092431] RAX: ffffb1b9cb081000 RBX: 0000000000000020 RCX: ffffb1b9e2f1fb88
[71023.105586] RDX: 00000000ffffffff RSI: ffffb1b9c6bdb3d8 RDI: ffffb1b9caf3d000
[71023.118693] RBP: 0000000000000002 R08: 0000000000000002 R09: 000000000000191f
[71023.131773] R10: ffffb1b9c6bdb000 R11: 0000000000001000 R12: 0000000000001900
[71023.144734] R13: 0000000000000000 R14: ffffb1b9caf3d000 R15: ffffb1b9e2f1fba4
[71023.157582] FS:  0000000000000000(0000) GS:ffff9f0b50600000(0000) knlGS:0000000000000000
[71023.171326] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[71023.182657] CR2: 00007fb8f96f11a0 CR3: 0000000963a0a003 CR4: 00000000007606f0
[71023.195428] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[71023.208166] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[71023.220839] PKRU: 55555554
[71023.229046] Call Trace:
[71023.236894]  ? ocf_cache_volume_io_complete_generic+0x80/0x80 [cas_cache]
[71023.249080]  ? ocf_cache_volume_io_complete_generic+0x80/0x80 [cas_cache]
[71023.261136]  ocf_metadata_passive_update+0x13f/0x1f0 [cas_cache]
[71023.272396]  ocf_cache_volume_submit_io+0xe3/0x130 [cas_cache]
[71023.283478]  blkdev_handle_bio_noflush+0x201/0x510 [cas_cache]
[71023.294496]  _casdsk_exp_obj_make_rq_fn+0x80/0x1d0 [cas_disk]
[71023.305395]  generic_make_request+0xcf/0x310
[71023.314796]  ? bio_add_page+0x42/0x50
[71023.323559]  drbd_submit_peer_request+0x2b1/0x400 [drbd]
[71023.333880]  receive_Data+0x6ae/0xeb0 [drbd]
[71023.343025]  ? receive_RSDataReply+0x2a0/0x2a0 [drbd]
[71023.352863]  ? receive_RSDataReply+0x2a0/0x2a0 [drbd]
[71023.362568]  drbd_receiver+0x4b1/0x640 [drbd]
[71023.371544]  ? do_retry+0x1d0/0x1d0 [drbd]
[71023.380232]  drbd_thread_setup+0x5a/0xb0 [drbd]
[71023.389332]  ? do_retry+0x1d0/0x1d0 [drbd]
[71023.397858]  kthread+0x112/0x130
[71023.405397]  ? kthread_flush_work_fn+0x10/0x10
[71023.414057]  ret_from_fork+0x35/0x40
[71023.421732] Modules linked in: drbd_transport_tcp(OE) drbd(OE) cas_cache(OE) cas_disk(OE) xt_CHECKSUM ipt_MASQUERADE xt_conntrack ipt_REJECT nf_reject_ipv4 nft_compat nft_counter nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c nls_utf8 isofs nf_tables nfnetlink loop tun rpcsec_gss_krb5 bridge auth_rpcgss stp llc nfsv4 dns_resolver nfs lockd grace fscache sunrpc vfat fat intel_rapl_msr intel_rapl_common isst_if_common iTCO_wdt iTCO_vendor_support skx_edac nfit libnvdimm x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm ipmi_ssif irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel intel_cstate intel_uncore intel_rapl_perf mei_me pcspkr ipmi_si ioatdma i2c_i801 joydev lpc_ich dca ipmi_devintf mei wmi ipmi_msghandler acpi_power_meter acpi_pad ip_tables ext4 mbcache jbd2 sd_mod sg i2c_algo_bit drm_vram_helper drm_ttm_helper ttm drm_kms_helper syscopyarea sysfillrect ahci sysimgblt fb_sys_fops libahci nvme i40e crc32c_intel nvme_core libata drm
[71023.421767]  [last unloaded: cas_disk]
```

## Your Environment

* OpenCAS version (commit hash or tag): 21.12.0.0589.master
* Operating System: RHEL 8.3

### LINKED ISSUE #1000: [21.12] Kernel BUG on secondary node at ocf_lru.c:183!
## Description

Occurred after starting syncing optane to cas-cache-1.

## Steps to Reproduce

1. Start standby cache on secondary node
2. Configure and create a DRBD device (optane on primary + cas-cache-1 on secondary)
3. Set the device as primary on the primary node

## Logs

```
[88056.711486] ------------[ cut here ]------------
[88056.722761] kernel BUG at /root/open-cas-linux/modules/cas_cache/src/ocf/ocf_lru.c:183!
[88056.737420] invalid opcode: 0000 [#1] SMP PTI
[88056.748346] CPU: 0 PID: 29846 Comm: drbd_r_caches-p Kdump: loaded Tainted: G           OE    --------- -  - 4.18.0-240.el8.x86_64 #1
[88056.790987] RIP: 0010:remove_lru_list_nobalance+0xfe/0x110 [cas_cache]
[88056.804563] Code: 89 63 08 44 89 e6 4c 89 ff e8 ce 85 fe ff 44 89 68 04 eb b3 0f 0b 44 89 6b 04 44 89 ee 4c 89 ff e8 b7 85 fe ff 44 89 20 eb 9d <0f> 0b 0f 0b 0f 1f 40 00 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00
[88056.836708] RSP: 0018:ffffb6414a2ebad0 EFLAGS: 00010246
[88056.848568] RAX: ffffb6414b8bc800 RBX: ffffb6414770a4fc RCX: ffffb6414770a400
[88056.862324] RDX: 0000000000017000 RSI: ffffb64146df5378 RDI: ffffb6414adcd000
[88056.876059] RBP: ffffb6414b8bc8ca R08: 0000000000000000 R09: ffffb6414adcec20
[88056.889768] R10: ffffb64146df5000 R11: 0000000000001000 R12: 00000000ffffffff
[88056.903318] R13: ffffb6414adcd088 R14: 00000000000170fa R15: ffffb6414adcd000
[88056.916760] FS:  0000000000000000(0000) GS:ffff9b42d0600000(0000) knlGS:0000000000000000
[88056.931108] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[88056.943022] CR2: 00007f3b26a65d68 CR3: 00000009a5c0a006 CR4: 00000000007606f0
[88056.956311] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[88056.969479] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[88056.982512] PKRU: 55555554
[88056.991584] Call Trace:
[88057.000126]  ocf_lru_repart_locked.isra.13+0x86/0x100 [cas_cache]
[88057.011891]  ocf_lru_repart+0x47/0x60 [cas_cache]
[88057.022240]  passive_io_resume+0x45d/0x890 [cas_cache]
[88057.032906]  ? ocf_cache_volume_io_complete_generic+0x80/0x80 [cas_cache]
[88057.045195]  ? ocf_cache_volume_io_complete_generic+0x80/0x80 [cas_cache]
[88057.057358]  ocf_metadata_passive_update+0x13f/0x1f0 [cas_cache]
[88057.068683]  ocf_cache_volume_submit_io+0xe3/0x130 [cas_cache]
[88057.079739]  blkdev_handle_bio_noflush+0x201/0x510 [cas_cache]
[88057.090697]  _casdsk_exp_obj_make_rq_fn+0x80/0x1d0 [cas_disk]
[88057.101524]  generic_make_request+0xcf/0x310
[88057.110775]  ? bio_add_page+0x42/0x50
[88057.119275]  drbd_submit_peer_request+0x2b1/0x400 [drbd]
[88057.129388]  receive_RSDataReply+0x197/0x2a0 [drbd]
[88057.139029]  ? decode_header+0x17/0x110 [drbd]
[88057.148123]  ? w_e_reissue+0x160/0x160 [drbd]
[88057.157029]  drbd_receiver+0x4b1/0x640 [drbd]
[88057.165781]  ? do_retry+0x1d0/0x1d0 [drbd]
[88057.174153]  drbd_thread_setup+0x5a/0xb0 [drbd]
[88057.182848]  ? do_retry+0x1d0/0x1d0 [drbd]
[88057.191431]  kthread+0x112/0x130
[88057.198982]  ? kthread_flush_work_fn+0x10/0x10
[88057.207480]  ret_from_fork+0x35/0x40
[88057.214985] Modules linked in: cas_cache(OE) cas_disk(OE) drbd_transport_tcp(OE) drbd(OE) xt_CHECKSUM ipt_MASQUERADE xt_conntrack ipt_REJECT nf_reject_ipv4 nft_compat nft_counter nft_chain_nat nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c nls_utf8 isofs nf_tables nfnetlink tun loop bridge stp llc rpcsec_gss_krb5 auth_rpcgss nfsv4 dns_resolver nfs lockd grace fscache sunrpc vfat fat ipmi_ssif intel_rapl_msr intel_rapl_common isst_if_common iTCO_wdt iTCO_vendor_support skx_edac nfit libnvdimm x86_pkg_temp_thermal intel_powerclamp coretemp kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul ghash_clmulni_intel intel_cstate ipmi_si intel_uncore pcspkr mei_me intel_rapl_perf ipmi_devintf joydev ioatdma i2c_i801 lpc_ich mei dca wmi ipmi_msghandler acpi_power_meter acpi_pad ip_tables ext4 mbcache jbd2 sd_mod sg i2c_algo_bit drm_vram_helper drm_ttm_helper ttm drm_kms_helper syscopyarea sysfillrect ahci sysimgblt fb_sys_fops libahci i40e crc32c_intel nvme drm nvme_core libata
[88057.215020]  [last unloaded: cas_disk]
```

## Your Environment

* OpenCAS version (commit hash or tag): 21.12.0.0589.master
* Operating System: RHEL 8.3

### PR DESCRIPTION
**Pull request by arutk**
Fixes #1000 
Fixes #998

### CODE REVIEW

**Review by mmichal10 — DISMISSED** [review]

**Review by mmichal10 — APPROVED** [review]

File: casadm/cas_lib.c [hunk 1]
```diff
@@ -3004,12 +3004,15 @@ int failover_activate(int cache_id, const char *cache_device)
...
-			return FAILURE;
-		}
+	if (set_device_path(data.cache_path, sizeof(data.cache_path),
+			    cache_device, MAX_STR_LEN) != SUCCESS) {
+		return FAILURE;
 	}
 
-	return cas_ioctl(KCAS_IOCTL_FAILOVER_ACTIVATE, &data);
+	if (cas_ioctl(KCAS_IOCTL_FAILOVER_ACTIVATE, &data) != SUCCESS) {
+		print_err(data.ext_err_code ? : KCAS_ERR_SYSTEM);
```
Comment (rafalste) [inline casadm/cas_lib.c:3013]: Shouldn't it print *data.ext_err_code* if exists?

File: modules/cas_cache/layer_cache_management.c [hunk 2]
```diff
@@ -1830,11 +1830,8 @@ int cache_mngt_prepare_cache_device_cfg(struct ocf_mngt_cache_device_config *cfg
...
 
-	if (cfg->uuid.size == 1) {
-		// empty string means empty uuid
-		cfg->uuid.size = 0;
-		return 0;
-	}
+	if (cfg->uuid.size <= 1)
+		return -OCF_ERR_INVAL;
 
 	if (cfg->uuid.size > 1) {
```
Comment (rafalste) [inline modules/cas_cache/layer_cache_management.c:1836]: No need for this conditional anymore.

**Review by rafalste — APPROVED** [review]

**Review by mmichal10 — APPROVED** [review]
