### PR TITLE
fix for issue #1023

### LINKED ISSUE #1023: [21.12] Better error when core size is mismatched during activation/load
## Description

After slightly resizing core device activation (or load) fails (as it should), but the error message is non-informative.

## Current behavior

```
# casadm -S -d /dev/drbd0 --load
Error inserting cache 1
Failed to insert cache
```
The same errors in opencas.log, no info in dmesg

## Proposed behavior
```
# casadm -S -d /dev/drbd0 --load
Error inserting cache 1
Failed to insert cache
<Information why the cache wasn't loaded/activated>
```
The same info in opencas.log, maybe info in dmesg

## Your Environment

* OpenCAS version (commit hash or tag): 21.12.0.0595.master

### PR DESCRIPTION
**Pull request by pdebski21**
Better error for core size mismatch during activation/load

Fixes #1023 

Signed-off-by: Piotr Debski <piotr.debski@intel.com>

### CODE REVIEW

**Comment by robertbaldyga** [comment]
retest this please

File: casadm/extended_err_msg.c [hunk 1]
```diff
@@ -182,6 +182,11 @@ struct {
 		OCF_ERR_STANDBY_ATTACHED,
 		"Cache device is attached, please detach it first with --standby --detach"
 	},
+	{
+		OCF_ERR_CORE_SIZE_MISMATCH,
+		"Core volume size does not match with"
```
Comment (arutk) [inline casadm/extended_err_msg.c:187]: "to match something" (without with) is grammatically correct

Comment (pdebski21) [reply casadm/extended_err_msg.c]: corrected

**Review by arutk — APPROVED** [review]

**Review by jfckm — APPROVED** [review]
