### PR TITLE
When core exported object name exists activation fails and cache is stopped

### LINKED ISSUE #1022: [21.12] Activation succeeds when a file with core exported object name exists
## Description

When a regular file /dev/cas1-1 exists, standby cache activation succeeds.

## Expected Behavior

Same as on load in similar situation
```
# casadm --failover-activate --cache-id 1 --cache-device /dev/drbd0
Error inserting cache 1
Could not create exported object because file in /dev directory exists
Error occurred, please see syslog (/var/log/messages) for details.
```

## Actual Behavior

```
# casadm --failover-activate --cache-id 1 --cache-device /dev/drbd0
Could not create exported object because file in /dev directory exists
# casadm -L
type    id   disk             status    write policy   device
cache   1    /dev/drbd0       Running   wb             -
└core   1    /dev/nvme0n1p1   Active    -              /dev/cas1-1
```

## Steps to Reproduce

1. Standard DRBD setup
2. Fail primary node
3. `touch /dev/cas1-1` before activation
4. Activate standby cache

## Your Environment

* OpenCAS version (commit hash or tag): 21.12.0.0595.master

### PR DESCRIPTION
**Pull request by pdebski21**
fixes #1022 

Signed-off-by: Piotr Debski <piotr.debski@intel.com>

### CODE REVIEW

**Comment by mmichal10** [comment]
Would you mind updating ocf to the newest version? It would allow to close #1018 :)

File: modules/cas_cache/layer_cache_management.c [hunk 1]
```diff
@@ -2353,12 +2353,27 @@ int cache_mngt_activate(struct ocf_mngt_cache_standby_activate_config *cfg,
...
+	if (result)
+        goto err;
 
+    cas_lazy_thread_stop(context->rollback_thread);
 	if (result)
 		goto err_free_context;
 
-	result = _cache_start_finalize(cache, -1, true);
+err:
+    _cache_mngt_async_context_init(&context->async);
```
Comment (mmichal10) [inline modules/cas_cache/layer_cache_management.c:2365]: I'm not sure if calling `_cache_mngt_async_context_init()` for the second time is a good idea as it calls `init_completion()` which is not a correct usages of completions. According to [the documentation ](https://www.kernel.org/doc/Documentation/scheduler/completion.txt) you are supposed call `reinit_completion()`.

File: modules/cas_cache/layer_cache_management.c [hunk 2]
```diff
@@ -2353,12 +2353,27 @@ int cache_mngt_activate(struct ocf_mngt_cache_standby_activate_config *cfg,
 	if (result == -KCAS_ERR_WAITING_INTERRUPTED)
 		goto out_cache_put;
 
-	cas_lazy_thread_stop(context->rollback_thread);
+	result = _cache_start_finalize(cache, -1, true);
+	if (result)
+        goto err;
 
+    cas_lazy_thread_stop(context->rollback_thread);
 	if (result)
```
Comment (mmichal10) [inline modules/cas_cache/layer_cache_management.c:2361]: If the activation and start_finalize have been successful you don't want to stop the cache you just activated so I guess the condition should be `result == 0`

File: modules/cas_cache/layer_cache_management.c [hunk 3]
```diff
@@ -2353,12 +2353,27 @@ int cache_mngt_activate(struct ocf_mngt_cache_standby_activate_config *cfg,
...
+
+    rollback_result = _cache_mngt_async_caller_set_result(&context->async,
+                    rollback_result);
+    
+    if (rollback_result != -KCAS_ERR_WAITING_INTERRUPTED)
+        kfree(context);
+    
+    return result;
 
 err_free_context:
```
Comment (mmichal10) [inline modules/cas_cache/layer_cache_management.c:2378]: Personally, I would add a second label here (i.e. `finish`, `end` or `our_success`) because `err_free_context` suggests that an error occurred which is not true if the code jumpes here after a successful activation. Having two labels will increase readability

File: modules/cas_cache/layer_cache_management.c [hunk 4]
```diff
@@ -2353,12 +2353,27 @@ int cache_mngt_activate(struct ocf_mngt_cache_standby_activate_config *cfg,
...
+	result = _cache_start_finalize(cache, -1, true);
+	if (result)
+        goto err;
 
+    cas_lazy_thread_stop(context->rollback_thread);
 	if (result)
 		goto err_free_context;
 
-	result = _cache_start_finalize(cache, -1, true);
+err:
```
Comment (mmichal10) [inline modules/cas_cache/layer_cache_management.c:2364]: How about `err_finalize`?

**Review by mmichal10 — APPROVED** [review]

File: modules/cas_cache/layer_cache_management.c [hunk 5]
```diff
@@ -2343,7 +2343,7 @@ int cache_mngt_activate(struct ocf_mngt_cache_standby_activate_config *cfg,
 		result = PTR_ERR(context->rollback_thread);
 		goto err_free_context;
 	}
-	_cache_mngt_async_context_init(&context->async);
+	 _cache_mngt_async_context_init(&context->async);
```
Comment (mmichal10) [inline modules/cas_cache/layer_cache_management.c:2346]: Unneeded space

File: modules/cas_cache/layer_cache_management.c [hunk 6]
```diff
@@ -2353,13 +2353,30 @@ int cache_mngt_activate(struct ocf_mngt_cache_standby_activate_config *cfg,
 	if (result == -KCAS_ERR_WAITING_INTERRUPTED)
 		goto out_cache_put;
 
+	result = _cache_start_finalize(cache, -1, true);
```
Comment (mmichal10) [inline modules/cas_cache/layer_cache_management.c:2356]: Before calling finalize you have to make sure that `ocf_mngt_cache_standby_activate()` finished successfully

File: modules/cas_cache/layer_cache_management.c [hunk 7]
```diff
@@ -2353,13 +2353,30 @@ int cache_mngt_activate(struct ocf_mngt_cache_standby_activate_config *cfg,
...
+	if (result)
+		goto err_finalize;
```
[the remark this answers is not in the document]
Comment (pdebski21) [reply modules/cas_cache/layer_cache_management.c]: Now handling unsuccessfull activate is the same as for finalize so goto err will be better for code oraganization.

**Review by mmichal10 — APPROVED** [review]

**Review by robertbaldyga — APPROVED** [review]

**Review by mmichal10 — APPROVED** [review]
