### PR TITLE
Split big IO requests

### LINKED ISSUE #855: Incorrect file md5 sum after interrupted core removal
## Description

After interrupting core removal operation, the test file md5 sum was incorrect. The file was on xfs filesystem.
Similar test with interrupting cache stop operation passed.

## Steps to Reproduce

1. Start a cache in WB mode
2. Set the cleaning policy to nop
3. Create a xfs filesystem on a core device
4. Add the core to the cache
5. Mount the exported object
6. Create a big test file (NOT in the mounted location) and count its md5 sum
7. Copy the test file to the mounted location
8. Call 'sync' and unmount the filesystem
8. Run 'remove core' command
9. Wait for progress to reach 70% (flushing data) and then interrupt the removal
10. Re-mount the filesystem and call 'sync'
11. Count the test file md5 sum on mounted filesystem

## Your Environment

* OpenCAS version (commit hash or tag): 8c2ab0fac60656cff466151b47378d6c647c4992
* Operating System: Centos 7.9
* Kernel version: 5.10
* Cache device type (NAND/Optane/other): Optane
* Core device type (HDD/SSD/other): SATA SSD
* Cache configuration:
* * Cache mode: (default: wt) wb
* * Cache line size: (default: 4)
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru) nop
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

### LINKED ISSUE #856: FIO IO error - cache line size 4k, XFS
## Description

Test checks different fio IO engines. Issues occur only with configuration from title, regardless of IO engine used. Noticed in WB, WA and WT mode.

## Actual Behavior

FIO ended with error:
`fio: pid=0, err=5/file:filesetup.c:249, func=fsync, error=Input/output error`

## Steps to Reproduce

1. Start a cache with 4k cache line size
2. Add a core
3. Create XFS on the exported object
4. Mount the filesystem
5. Run fio (engines can be different, CPUs correspond to cache device numa node):
`fio --eta=always --output-format=json --output=fio_output --group_reporting --direct=1 --ioengine=posixaio --runtime=900 --time_based --readwrite=randrw --rwmixwrite=30 --verify=pattern --verify_pattern=0x74F81AC766A4BC7E4327056B74098EA9 --do_verify=1 --cpus_allowed=0-17,36-53 --cpus_allowed_policy=split --size=1073741824 --filename=/mnt/test/fio_test --name=fio`

## Your Environment

* OpenCAS version (commit hash or tag): eaa2f54ec160539b4fab4815df254da4c1807908
* Operating System: Centos 7.9
* Kernel version: 5.10
* Cache device type (NAND/Optane/other): Optane
* Core device type (HDD/SSD/other): HDD
* Cache configuration:
* * Cache mode: differrent
* * Cache line size: 4k
* * Promotion policy: (default: always)
* * Cleaning policy: (default: alru)
* * Sequential cutoff policy: (default: full)
* Other (e.g. _lsblk_, _casadm -P_, _casadm -L_)

### LINKED ISSUE #866: request map allocation failures for large bio
## Description
In multiple test scenarios, especially involving buffered I/O to file system, the following warning is printed and I/O to CAS fails:

[12174.020195] ------------[ cut here ]------------
[12174.032817] WARNING: CPU: 50 PID: 71972 at mm/page_alloc.c:4935 __alloc_pages_nodemask+0x2aa/0x310
[12174.050812] Modules linked in: cas_cache(O) cas_disk(O) xfs nvme nvme_core xt_CHECKSUM iptable_mangle xt_MASQUERADE iptable_nat nf_nat xt_conntrack nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 libcrc32c tun bridge stp llc ebtable_filter ebtables ip6table_filter ip6_tables bpfilter rpcsec_gss_krb5 auth_rpcgss oid_registry nfsv4 nfs lockd grace nfs_ssc fscache sunrpc vfat fat iTCO_wdt intel_rapl_msr iTCO_vendor_support intel_rapl_common iosf_mbi sb_edac x86_pkg_temp_thermal intel_powerclamp ipmi_si coretemp ftdi_sio crct10dif_pclmul ipmi_devintf acpi_power_meter crc32_pclmul ipmi_msghandler ioatdma i2c_i801 wmi ghash_clmulni_intel i2c_smbus lpc_ich kvm_intel acpi_pad igb i2c_algo_bit xhci_pci dca ptp crc32c_intel pps_core xhci_hcd i2c_core fuse [last unloaded: cas_disk]
[12174.189192] CPU: 50 PID: 71972 Comm: cas_io_1_50 Tainted: G S      W IO L    5.10.32-t1.el7.twitter.x86_64 #1
[12174.210706] Hardware name: Intel Corporation S2600WT2/S2600WT2, BIOS SE5C610.86B.01.01.1008.031920151331 03/19/2015
[12174.233061] RIP: 0010:__alloc_pages_nodemask+0x2aa/0x310
[12174.249324] Code: 00 00 bd 01 00 00 00 48 89 44 24 08 e9 1b fe ff ff 48 89 c7 e8 c7 63 fc ff e9 83 fe ff ff 81 e7 00 20 00 00 0f 85 3d ff ff ff <0f> 0b 31 ed e9 36 ff ff ff 31 c0 e9 e1 fd ff ff 65 48 8b 04 25 00
[12174.291379] RSP: 0018:ffffbc4089d57dc8 EFLAGS: 00010246
[12174.307670] RAX: 0000000000000000 RBX: ffff90a4900f6a48 RCX: 0000000000000000
[12174.326271] RDX: 0000000000000000 RSI: 000000000000000b RDI: 0000000000000000
[12174.344834] RBP: 000000000000000b R08: ffff90b089da2ec8 R09: 00000000000001d9
[12174.363369] R10: 0000000000000000 R11: 000000000002f380 R12: 000000000000000b
[12174.381883] R13: 0000000000000d00 R14: 0000000000000282 R15: ffff90ace8fa7f80
[12174.400324] FS:  0000000000000000(0000) GS:ffff90abdfc00000(0000) knlGS:0000000000000000
[12174.420038] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[12174.437140] CR2: 00007fdb01b190a0 CR3: 00000004fa60a001 CR4: 00000000001706e0
[12174.456026] Call Trace:
[12174.469499]  kmalloc_order+0x24/0xe0
[12174.484302]  kmalloc_order_trace+0x19/0x80
[12174.499779]  ocf_req_alloc_map.part.7+0x25/0x70 [cas_cache]
[12174.517067]  ocf_engine_pop_req+0x91/0xe0 [cas_cache]
[12174.533825]  ocf_queue_run_single+0xf/0x30 [cas_cache]
[12174.550787]  ocf_queue_run+0x23/0x40 [cas_cache]
[12174.567178]  _cas_io_queue_thread+0x5a/0xf0 [cas_cache]
[12174.584394]  ? finish_wait+0x80/0x80
[12174.599787]  ? env_mpool_del+0x60/0x60 [cas_cache]
[12174.616631]  kthread+0x116/0x130
[12174.631646]  ? kthread_park+0x80/0x80
[12174.647178]  ret_from_fork+0x22/0x30
[12174.662632] ---[ end trace cd6af8719ffe64a5 ]---

## Expected Behavior
No warning

## Steps to Reproduce
See linked issues

## Possible Fix
OCF should not be forced to handle allocations of excessive size.

### PR DESCRIPTION
**Pull request by robertbaldyga**
Fixes #866 
Fixes #856 
Fixes #855

### CODE REVIEW

File: modules/cas_cache/volume/vol_block_dev_top.c [hunk 1]
```diff
@@ -247,22 +260,81 @@ static void _blockdev_handle_data(ocf_core_t core, struct bio *bio)
...
+	master_ctx.start_time = cas_generic_start_io_acct(bio);
+	for (sectors = bio_sectors(bio); sectors > 0;) {
+		if (sectors <= max_io_sectors) {
+			split = bio;
+			sectors = 0;
+		} else {
+			to_submit = max_io_sectors;
+			unaligned = CAS_BIO_BISECTOR(bio) % align_sectors;
+			if (unlikely(unaligned))
+				to_submit +=  unaligned - align_sectors;
```
Comment (arutk) [inline modules/cas_cache/volume/vol_block_dev_top.c:319]: You mean to end current I/O at an aligned adress? Then you have to change this to either
  to_submit -= unaligned - align_sectors;
or
  to_submit += align_sectors - unaligned;
 I think the former is better as the I/O size is smaller than max_io_sectors

File: modules/cas_cache/volume/vol_block_dev_top.c [hunk 2]
```diff
@@ -247,22 +260,81 @@ static void _blockdev_handle_data(ocf_core_t core, struct bio *bio)
...
+
+	_block_dev_complete_data(master_ctx.data, 0);
+
+	return;
+
+err:
+	if (master_ctx.data)
+		_block_dev_complete_data(master_ctx.data, error);
+	else
+		CAS_BIO_ENDIO(bio, CAS_BIO_BISIZE(bio), CAS_ERRNO_TO_BLK_STS(error));
```
Comment (arutk) [inline modules/cas_cache/volume/vol_block_dev_top.c:337]: My understanding is that this assumes split bio is not created. This might not be the case in case of error in the first call to _blockdev_handle_data_single.

**Review by arutk — CHANGES_REQUESTED** [review]

File: modules/cas_cache/volume/vol_block_dev_top.c [hunk 3]
```diff
@@ -195,19 +195,43 @@ static void _blockdev_defer_bio(ocf_core_t core, struct bio *bio,
 	queue_work(bvol->expobj_wq, &context->io_work);
 }
 
+static void _block_dev_complete_data(struct blk_data *master, int error)
+{
+	master->error = master->error ?: error;
```
[the remark this answers is not in the document]
Comment (robertbaldyga) [reply modules/cas_cache/volume/vol_block_dev_top.c:200]: This pattern is extremely common in both OCL and OCF.

File: modules/cas_cache/volume/vol_block_dev_top.c (hunk 1 above)
Comment (robertbaldyga) [reply modules/cas_cache/volume/vol_block_dev_top.c:319]: I'd like to compensate unalignment in the first I/O, so that consequent I/Os will be aligned.

File: modules/cas_cache/volume/vol_block_dev_top.c (hunk 2 above)
Comment (robertbaldyga) [reply modules/cas_cache/volume/vol_block_dev_top.c:340]: Good catch. Fixed.

File: modules/cas_cache/volume/vol_block_dev_top.c (hunk 1 above)
Comment (robertbaldyga) [reply modules/cas_cache/volume/vol_block_dev_top.c]: Fixed.

**Review by mmichal10 — APPROVED** [review]

**Review by rafalste — APPROVED** [review]
