### PR TITLE
Disable the possibility to use the 'load' and 'force' flags at once

### LINKED ISSUE #378: Loading cache with --force flag prevents recovery
### Description
If you try to run `casadm -S --load --force -d <device>` on a cache device that didn't shutdown cleanly under load the loadprocedure is going to fail and will report CRC error in dmesg. The recovery won't even be attempted as reported in dmesg.

### Reproduction steps
1. Create wb cache
2. Dirty the cache
3. Start flushing
4. Power failure
5. Try to load the cache with `--force` flag

### Expected results
Cache will load (or flags combination will be rejected) or attempt recovery

### Actual results
Cache fails to load, CRC error reported in dmesg, recovery not attempted

### Suggested solutions
First: integrate OCF fix for issue [361](https://github.com/Open-CAS/ocf/issues/361)
Second: Add nice handling of such case. I think that just rejecting `--load` and `--force` flags would be enough - this combination doesn't make sense anyways.

### PR DESCRIPTION
**Pull request by Ostrokrzew**
Discard wrong combination of flags in `--start-cache` command.
Print error message.
Add test to check the above functionality.

Closes #378

### CODE REVIEW

File: casadm/cas_main.c [hunk 1]
```diff
@@ -294,6 +294,11 @@ int handle_start()
 	int status;
 	struct stat device_info;
 
+	if (command_args_values.state && command_args_values.force) {
```
Comment (robertbaldyga) [inline casadm/cas_main.c:297]: Please explicitly compare state with define value for better readability of the code:
`command_args_values.state == CACHE_INIT_LOAD`

File: test/functional/tests/cli/test_cli_start_stop.py [hunk 2]
```diff
@@ -80,3 +82,30 @@ def test_cli_add_remove_default_value(shortcut):
...
+def test_cli_load_and_force():
+    """
+        title: Test if it is possible to use 'load' and 'force' flag at once
+        description: |
+          Start new cache instance
+          Stop cache instance
+          Try to start cache with 'load' and 'force' options at the same time
+        pass_criteria:
+          - Command should fail
+          - Proper communicate should be received
```
Comment (katlapinka) [inline test/functional/tests/cli/test_cli_start_stop.py:97]: "proper message", because "communicate" is a verb

File: test/functional/tests/cli/test_cli_start_stop.py [hunk 3]
```diff
@@ -80,3 +82,30 @@ def test_cli_add_remove_default_value(shortcut):
...
+        cache_device = cache_device.partitions[0]
+        cache = casadm.start_cache(cache_device)
+
+    with TestRun.step("Stop cache."):
+        cache.stop()
+
+    with TestRun.step("Try to load cache with 'force'."):
+        output = TestRun.executor.run(start_cmd(
+            cache_dev=cache_device.system_path, force=True, load=True))
+        cli_messages.check_msg(output, cli_messages.load_and_force)
```
Comment (katlapinka) [inline test/functional/tests/cli/test_cli_start_stop.py:111]: please check also an exit code

File: test/functional/tests/cli/test_cli_start_stop.py [hunk 4]
```diff
@@ -7,6 +7,8 @@
 import pytest
 
 from api.cas import casadm, casadm_parser
+from api.cas.cli import start_cmd
+from api.cas import cli_messages
```
Comment (rafalste) [inline test/functional/tests/cli/test_cli_start_stop.py:11]: You can add cli_messages to previous modules imported from api.cas (two lines above) just for cleanliness.

File: test/functional/tests/cli/test_cli_start_stop.py [hunk 5]
```diff
@@ -80,3 +82,32 @@ def test_cli_add_remove_default_value(shortcut):
...
+
+
+@pytest.mark.require_disk("cache", DiskTypeSet([DiskType.optane, DiskType.nand]))
+def test_cli_load_and_force():
+    """
+        title: Test if it is possible to use 'load' and 'force' flag at once
+        description: |
+          Start new cache instance
+          Stop cache instance
+          Try to start cache with 'load' and 'force' options at the same time
```
Comment (katlapinka) [inline test/functional/tests/cli/test_cli_start_stop.py:94]: There shouldn't be steps listed in description, but one generic sentence

File: test/functional/tests/cli/test_cli_start_stop.py [hunk 6]
```diff
@@ -80,3 +82,32 @@ def test_cli_add_remove_default_value(shortcut):
...
+        pass_criteria:
+          - Command should fail
```
Comment (katlapinka) [inline test/functional/tests/cli/test_cli_start_stop.py:96]: Maybe "Start cache command with both 'force' and 'load' options should fail" ? Because it seems like any command should fail

File: test/functional/tests/cli/test_cli_start_stop.py [hunk 7]
```diff
@@ -80,3 +82,32 @@ def test_cli_add_remove_default_value(shortcut):
         TestRun.fail("No cache should be present after stopping the cache")
     if output.stdout != "No caches running":
         TestRun.fail(f"Invalid message, expected 'No caches running', got {output.stdout}")
+
+
+@pytest.mark.require_disk("cache", DiskTypeSet([DiskType.optane, DiskType.nand]))
+def test_cli_load_and_force():
+    """
+        title: Test if it is possible to use 'load' and 'force' flag at once
```
Comment (katlapinka) [inline test/functional/tests/cli/test_cli_start_stop.py:90]: "... to use start command with 'load' and 'force' flags at once"

File: test/functional/tests/cli/test_cli_start_stop.py [hunk 8]
```diff
@@ -80,3 +81,32 @@ def test_cli_add_remove_default_value(shortcut):
...
         TestRun.fail(f"Invalid message, expected 'No caches running', got {output.stdout}")
+
+
+@pytest.mark.require_disk("cache", DiskTypeSet([DiskType.optane, DiskType.nand]))
+def test_cli_load_and_force():
+    """
+        title: Test if it is possible to use start command with 'load' and 'force' flag at once
+        description: |
+          Try to start cache with 'load' and 'force' options at the same time
+          and check if it is not possible to do
```
Comment (rafalste) [inline test/functional/tests/cli/test_cli_start_stop.py:92]: Just a small suggestion:
`and make sure it is not possible`
