### PR TITLE
Fix adding core after core addition failure

### LINKED ISSUE #808: Sporadical problem with adding core device to the cache instance
## Description
There is a problem to add a core to the cache which results in error message like below:

> Error while adding core device to cache instance 1
> Cannot allocate memory

Problem occurs on RHEL 7.x

## Expected Behavior
Core should be added successfully

## Actual Behavior
This is impossible to add core

## Your Environment

* OpenCAS version (commit hash or tag):  21.03.0.0496.release
* Operating System: RHEL 7.9
* Kernel version: 3.10.0-1160.el7.x86_64
* Cache device type (NAND/Optane/other): Optane

### PR DESCRIPTION
**Pull request by Ostrokrzew**
caused by disallowed logical block size mismatch.

Cleanup exported object queue 
This patch fixes adding core after core addition failure.
The queue wasn't cleaned before and following core addition cannot
re-initialize queue properly.

Fixes #808

Signed-off-by: Slawomir Jankowski <slawomir.jankowski@intel.com>

### CODE REVIEW

**Review by arutk — APPROVED** [review]

File: modules/cas_cache/volume/vol_block_dev_top.c [hunk 1]
```diff
@@ -577,6 +577,18 @@ static void _blockdev_set_discard_properties(ocf_cache_t cache,
...
 }
 
+static void _blockdev_cleanup_queue(struct casdsk_disk *dsk)
+{
+	struct request_queue *exp_obj_q = NULL;
+
+	exp_obj_q = casdisk_functions.casdsk_exp_obj_get_queue(dsk);
+	BUG_ON(!exp_obj_q);
+
+	if (exp_obj_q) {
```
Comment (mmichal10) [inline modules/cas_cache/volume/vol_block_dev_top.c:587]: `if` is not necessary if you have `bug_on()`

File: modules/cas_disk/exp_obj.c [hunk 2]
```diff
@@ -652,6 +651,17 @@ struct request_queue *casdsk_exp_obj_get_queue(struct casdsk_disk *dsk)
...
+void casdsk_exp_obj_cleanup_queue(struct casdsk_disk *dsk)
+{
+	struct request_queue *exp_obj_q = NULL;
+
+	exp_obj_q = casdsk_exp_obj_get_queue(dsk);
+	BUG_ON(!exp_obj_q);
+
+	blk_cleanup_queue(exp_obj_q);
+}
+EXPORT_SYMBOL(casdsk_exp_obj_cleanup_queue);
```
Comment (robertbaldyga) [inline modules/cas_disk/exp_obj.c:663]: Why do we export this function? Is used only in this file, so it should be static.

**Review by robertbaldyga — CHANGES_REQUESTED** [review]

File: modules/cas_disk/exp_obj.c [hunk 3]
```diff
@@ -652,6 +651,17 @@ struct request_queue *casdsk_exp_obj_get_queue(struct casdsk_disk *dsk)
 }
 EXPORT_SYMBOL(casdsk_exp_obj_get_queue);
 
+void casdsk_exp_obj_cleanup_queue(struct casdsk_disk *dsk)
```
Comment (robertbaldyga) [inline modules/cas_disk/exp_obj.c:654]: We can pass `queue` directly to this function instead of `dsk`. Btw this will make this function one-liner, so maybe just call `blk_cleanup_queue()` directly where it's used?

**Review by robertbaldyga — CHANGES_REQUESTED** [review]

File: modules/cas_disk/exp_obj.c (hunk 3 above)
Comment (Ostrokrzew) [reply modules/cas_disk/exp_obj.c]: done

**Review by mmichal10 — APPROVED** [review]
